### ISSUE TITLE
Crear el StyleSheet para tamaños de fuente

### ISSUE THREAD

**Issue by jscortes23** [jscortes23/softech-mobile#9]
#Ante de comenzar ejecutar los siguientes comando uno a la vez:
`git pull`
`git fetch origin`
`git checkout nombre de la rama`

Luego cambiar de rama usando el el comando:

`git switch nombre de la rama`

Asegura te que aparezca el nombre de la rama en la terminal
>[!NOTE]
>Para tener la terminal como la de la imagen haz lo siguiente
>![Image](https://github.com/jscortes23/softech-mobile/assets/80847249/e08efcf2-eecd-47d3-bc3f-65f899c7df8a)

![Image](https://github.com/jscortes23/softech-mobile/assets/80847249/c4819e12-31e4-4c90-b490-bc641d1cc0fd)

El componente a crear debe tener la siguiente estructura para cada uno de los colores:

>[!NOTE]
>No olvidar importar las librerías necesarias

```javascript
export const styleFontSize = StyleSheet.create({
  largeTitle: {
    fontSize: fontSize.largeTitle,
  },
})

```

**Comment by isabellamonteroo** [comment]
export const styleFontSize = StyleSheet.create({
  largeTitle: {
    fontSize: 42,
  },
  title1: {
    fontSize: 32,
  },
  title2: {
    fontSize: 24,
  },
  subtitle1: {
    fontSize: 20,
  },
  subtitle2: {
    fontSize: 18,
  },
  body1: {
    fontSize: 16,
  },
  body2: {
    fontSize: 14,
  },
  caption1: {
    fontSize: 12,
  },
})
